# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
        secured_area:
            # ...
            form_login:
                # ...
                csrf_parameter: _csrf_security_token
                csrf_token_id: 'thetea'
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /login
                invalidate_session: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/job/^, role: ROLE_ADMIN }
        #- { path: ^/, role: ROLE_USER }
        - { path: /home, role: ROLE_USER }
        - { path: /profile, role: ROLE_USER }
        #- { path: /api-check-username, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: /api-check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }