<?php

namespace Job\JobBundle\Repository;

/**
 * JobTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
